services:
  postgres:
    image: postgres:16-alpine
    container_name: college-library-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
    ports:
      - "5432:5432"
    volumes:
      - library_postgres_data:/var/lib/postgresql/data

volumes:
  library_postgres_data:
